Feature/4.3 search filter books
Zokster9/Library-Valcon-Internship pull request #6
Opened 2023-03-15 08:44 UTC by Zokster9

Add search books, filter and sort

2023-03-15 13:48 UTC, sttevan requested changes

2023-03-15 13:48 UTC, sttevan commented on library-valcon-internship/src/components/Modals/ModalFilter/ModalFilter.tsx
> +const ModalFilter = ({ show, closeModal, applyFilter }: ModalFilterProps) => {
Hajde da odvojimo modal komponentu od filtera

neka modal bude neki genericki, sa dve akcije dissmiss i confirm i sa svim modalnim stilovimo, a filter odvojeno i da se bavi smao logikom za filter

2023-03-15 13:48 UTC, sttevan commented on library-valcon-internship/src/components/Modals/ModalFilter/ModalFilter.tsx
> +  const handleOnChangeLastName = ({ currentTarget }: FormEvent<HTMLInputElement>) => {
Ove cetiri funkcije su iste, optimizuj

2023-03-15 16:02 UTC, Zokster9 commented
Nisu sve pull request izmene jos pushovane

2023-03-16 10:08 UTC, sttevan requested changes

2023-03-16 10:08 UTC, sttevan commented on library-valcon-internship/src/components/SortIconButtons/SortIconButtons.css
> +.SortIconButtons {}
Je l nam treba ovo ako je prazno?

2023-03-16 10:08 UTC, vladimiragbaba98 commented on library-valcon-internship/src/components/Modals/Modal.tsx
> +    <div style={!show ? { visibility: 'hidden' } : {}} className='modal'>
If you use visibility hidden, element will still be present at the page. You should manage show / hide modal at the parent component and render it or not based on the condition

2023-03-16 10:15 UTC, vladimiragbaba98 commented on library-valcon-internship/src/components/Search/Search.tsx
> +      handleCloseModals()
You don't need handleCloseModals here if you already have it out of if-else, it will be executed anyway

2023-03-16 10:19 UTC, vladimiragbaba98 commented on library-valcon-internship/src/components/Search/Search.tsx
> +      <Modal show={showModal} closeModal={handleCloseModals} confirm={handleConfirm} >
You don't need to pass showModal prop to the modal - use the same approach as you are using at lines 122 and 123

2023-03-16 10:23 UTC, vladimiragbaba98 commented on library-valcon-internship/src/pages/HomePage/HomePage.tsx
>    const [ pageNumber, setPageNumber ] = useState(1)
You can have one object for pageable request and store pageNumber, pageLenght etc. there to avoid too many states and managing one by one

2023-03-16 10:36 UTC, merged